name: CI

on:
  push:

jobs:
  build-latex:
    name: "🏗️ LaTeX build"
    runs-on: ubuntu-20.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🏗️ Compile paper"
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: paper
          root_file: emnlp2021.tex
      - name: "📤 Upload paper"
        uses: actions/upload-artifact@v2
        with:
          path: paper/emnlp2021.pdf
          name: Paper
  test-python:
    name: "🧪 Python test"
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: "🧰 Install pipx"
        run: pip install --user pipx
      - name: "🧰 Install Pipenv"
        run: pipx install pipenv
      - name: "🧰 Install dependencies"
        run: pipenv install --deploy
      - name: "🧪 Check Python code format"
        run: pipenv run flake8
      - name: "🧪 Lint Python code"
        run: pipenv run pylint -E modern_talking
      - name: "🧪 Test Python code"
        run: pipenv run pytest --cov --cov-report=term --cov-report=xml || true
      - name: "📤 Upload test coverage"
        uses: actions/upload-artifact@v2
        with:
          path: coverage.xml
          name: Python test coverage
      - name: "📤 Publish test coverage"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
        
 